name: Test and Build Anchor

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: metadaoproject/setup-anchor@v2
        with:
          anchor-version: "0.30.1"
          node-version: "20"
          solana-cli-version: "1.18.9"

      - name: Configure Solana
        run: |
          # Set the cluster to Devnet
          solana config set --url https://api.devnet.solana.com

      - name: Generate new keypair
        run: solana-keygen new --no-bip39-passphrase

      - name: Airdrop SOL
        run: |
          # Airdrop SOL to the new keypair
          solana airdrop 2

      - name: Check solana config
        run: solana config get

      - name: Build Anchor program
        run: pnpm run anchor build
        shell: bash

      - name: Run Anchor tests
        run: pnpm run anchor test
        shell: bash
